/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import model.Controller;
import model.Person;

/**
 *
 * @author anujkumar
 */
public class DoctorAfterLogin extends javax.swing.JFrame {

    /**
     * Creates new form DoctorAfterLogin
     */
    static Controller system;
    static Person person;
    static Landing landing;

    
    public DoctorAfterLogin(Controller system , Person p) {
        initComponents();
        this.system=system;
        this.person=p;
        jLabelRole.setText(person.getRole().toString());
        jLabelName.setText(person.getName());
        jLabelUserName.setText(person.getuserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPaneDoctor = new javax.swing.JSplitPane();
        jPanelLeftPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelRole = new javax.swing.JLabel();
        jButtonViewEncounter = new javax.swing.JButton();
        jButtonEnterEncounter = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelRightPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLeftPane.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setText("Name  :");

        jLabel3.setText("Username :");

        jLabel4.setText("Role         :");

        jButtonViewEncounter.setText("View Encounter");
        jButtonViewEncounter.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.cyan, java.awt.Color.gray));
        jButtonViewEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewEncounterActionPerformed(evt);
            }
        });

        jButtonEnterEncounter.setText("Enter Encounter");
        jButtonEnterEncounter.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.cyan, java.awt.Color.gray));
        jButtonEnterEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterEncounterActionPerformed(evt);
            }
        });

        jButtonLogout.setText("Exit");
        jButtonLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.cyan, java.awt.Color.gray));
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLeftPaneLayout = new javax.swing.GroupLayout(jPanelLeftPane);
        jPanelLeftPane.setLayout(jPanelLeftPaneLayout);
        jPanelLeftPaneLayout.setHorizontalGroup(
            jPanelLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftPaneLayout.createSequentialGroup()
                .addGroup(jPanelLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLeftPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonEnterEncounter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonViewEncounter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelLeftPaneLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanelLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLeftPaneLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanelLeftPaneLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabelRole, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelLeftPaneLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLeftPaneLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelLeftPaneLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLeftPaneLayout.setVerticalGroup(
            jPanelLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftPaneLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLeftPaneLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(183, 183, 183))
                    .addGroup(jPanelLeftPaneLayout.createSequentialGroup()
                        .addGroup(jPanelLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLeftPaneLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLeftPaneLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabelRole, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131)))
                .addComponent(jButtonViewEncounter)
                .addGap(36, 36, 36)
                .addComponent(jButtonEnterEncounter)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPaneDoctor.setLeftComponent(jPanelLeftPane);

        jPanelRightPane.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanelRightPaneLayout = new javax.swing.GroupLayout(jPanelRightPane);
        jPanelRightPane.setLayout(jPanelRightPaneLayout);
        jPanelRightPaneLayout.setHorizontalGroup(
            jPanelRightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        jPanelRightPaneLayout.setVerticalGroup(
            jPanelRightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jSplitPaneDoctor.setRightComponent(jPanelRightPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneDoctor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneDoctor, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViewEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewEncounterActionPerformed
        // TODO add your handling code here:
        DoctorRightViewPatientHistory drvp=new DoctorRightViewPatientHistory(system,person);
        jSplitPaneDoctor.setRightComponent(drvp);
    }//GEN-LAST:event_jButtonViewEncounterActionPerformed

    private void jButtonEnterEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterEncounterActionPerformed
        // TODO add your handling code here:
        DoctorRightPatientHistoryEnter drph=new DoctorRightPatientHistoryEnter(system,person);
        jSplitPaneDoctor.setRightComponent(drph);
    }//GEN-LAST:event_jButtonEnterEncounterActionPerformed
    
    
    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        Landing l = new Landing();
        l.setVisible(true);
        
      
        
        
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorAfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorAfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorAfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorAfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new DoctorAfterLogin(system,person).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnterEncounter;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonViewEncounter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRole;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanelLeftPane;
    private javax.swing.JPanel jPanelRightPane;
    private javax.swing.JSplitPane jSplitPaneDoctor;
    // End of variables declaration//GEN-END:variables

    
}
