/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.patientDirectory;

/**
 *
 * @author renuka
 */
public class mainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    
    patientDirectory history;
    
    public mainJFrame() {
        initComponents();
        
        history = new patientDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        workArea = new javax.swing.JPanel();
        loginjLabel = new javax.swing.JLabel();
        diconjLabel = new javax.swing.JLabel();
        cadminjButton = new javax.swing.JButton();
        patientjLable = new javax.swing.JLabel();
        doctorjButton1 = new javax.swing.JButton();
        cadminjLabel = new javax.swing.JLabel();
        patientjButton1 = new javax.swing.JButton();
        sadminjLabel = new javax.swing.JLabel();
        sadminjButton1 = new javax.swing.JButton();
        welcomejLabel = new javax.swing.JLabel();
        hmsjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));

        loginjLabel.setBackground(new java.awt.Color(255, 255, 255));
        loginjLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 36)); // NOI18N
        loginjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginjLabel.setText("Login as...");
        loginjLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        diconjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/doctor (1).png"))); // NOI18N

        cadminjButton.setBackground(new java.awt.Color(204, 255, 204));
        cadminjButton.setFont(new java.awt.Font("Hoefler Text", 1, 18)); // NOI18N
        cadminjButton.setText("Community Admin");
        cadminjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        patientjLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/examination.png"))); // NOI18N

        doctorjButton1.setBackground(new java.awt.Color(204, 255, 204));
        doctorjButton1.setFont(new java.awt.Font("Hoefler Text", 1, 18)); // NOI18N
        doctorjButton1.setText("Doctor");
        doctorjButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        doctorjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorjButton1ActionPerformed(evt);
            }
        });

        cadminjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/unauthorized-person.png"))); // NOI18N

        patientjButton1.setBackground(new java.awt.Color(204, 255, 204));
        patientjButton1.setFont(new java.awt.Font("Hoefler Text", 1, 18)); // NOI18N
        patientjButton1.setText("Patient");
        patientjButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        patientjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientjButton1ActionPerformed(evt);
            }
        });

        sadminjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/engineer (1).png"))); // NOI18N

        sadminjButton1.setBackground(new java.awt.Color(204, 255, 204));
        sadminjButton1.setFont(new java.awt.Font("Hoefler Text", 1, 18)); // NOI18N
        sadminjButton1.setText("System Admin");
        sadminjButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        welcomejLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 2, 24)); // NOI18N
        welcomejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomejLabel.setText("Welcome to ");

        hmsjLabel.setFont(new java.awt.Font("ITF Devanagari Marathi", 3, 36)); // NOI18N
        hmsjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hmsjLabel.setText("Hospital Management System");

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workAreaLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(diconjLabel)
                        .addGap(188, 188, 188)
                        .addComponent(patientjLable)
                        .addGap(172, 172, 172)
                        .addComponent(cadminjLabel)
                        .addGap(245, 245, 245)
                        .addComponent(sadminjLabel))
                    .addGroup(workAreaLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(doctorjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231)
                        .addComponent(patientjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193)
                        .addComponent(cadminjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207)
                        .addComponent(sadminjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(workAreaLayout.createSequentialGroup()
                        .addGap(680, 680, 680)
                        .addComponent(welcomejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(workAreaLayout.createSequentialGroup()
                        .addGap(672, 672, 672)
                        .addComponent(loginjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(workAreaLayout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addComponent(hmsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(686, Short.MAX_VALUE))
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(welcomejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hmsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(loginjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diconjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientjLable, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadminjLabel)
                    .addComponent(sadminjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(patientjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadminjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sadminjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(484, Short.MAX_VALUE))
        );

        workAreaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {diconjLabel, patientjLable});

        workAreaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cadminjButton, doctorjButton1});

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientjButton1ActionPerformed
        // TODO add your handling code here:
        PatientJPanel panel = new PatientJPanel();
        splitPane.setRightComponent(panel);
   
    }//GEN-LAST:event_patientjButton1ActionPerformed

    private void doctorjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorjButton1ActionPerformed
        // TODO add your handling code here:
        DoctorJPanel panel = new DoctorJPanel();
        splitPane.setRightComponent(panel);
        
        
    }//GEN-LAST:event_doctorjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadminjButton;
    private javax.swing.JLabel cadminjLabel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel diconjLabel;
    private javax.swing.JButton doctorjButton1;
    private javax.swing.JLabel hmsjLabel;
    private javax.swing.JLabel loginjLabel;
    private javax.swing.JButton patientjButton1;
    private javax.swing.JLabel patientjLable;
    private javax.swing.JButton sadminjButton1;
    private javax.swing.JLabel sadminjLabel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JLabel welcomejLabel;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
