/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Controller;
import model.Encounter;
import model.Hospital;
import model.HospitalDirectory;
import model.Person;
import model.VitalRecord;

/**
 *
 * @author kb282
 */
public class PatientRightSearchHospital extends javax.swing.JPanel {

    /**
     * Creates new form PatientJplane
     */
    Person person;
    Controller system;
    public PatientRightSearchHospital(Controller system, Person person) {
        initComponents();
        this.person=person;
        this.system=system;
        HospitalDirectory hd=system.getHospitalDirectory();
        List <Hospital> hospital = hd.getHospitalList();
        populateTable(hospital);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHospital = new javax.swing.JTable();
        BtnSearch = new javax.swing.JButton();
        patientSearchCommunityName = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        patientSearchCity = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jTableHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "City", "Community"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableHospital);
        if (jTableHospital.getColumnModel().getColumnCount() > 0) {
            jTableHospital.getColumnModel().getColumn(2).setResizable(false);
        }

        BtnSearch.setText("Search ");
        BtnSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.cyan, java.awt.Color.gray));
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        patientSearchCommunityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientSearchCommunityNameActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        jLabel27.setText("Community Name :");

        patientSearchCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientSearchCityActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        jLabel28.setText("City :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(patientSearchCity, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(patientSearchCommunityName)
                            .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientSearchCommunityName)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientSearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnSearch)
                .addGap(143, 143, 143))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientSearchCommunityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientSearchCommunityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientSearchCommunityNameActionPerformed

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        // TODO add your handling code here:
        String cityName=patientSearchCity.getText();
        String communityName=patientSearchCommunityName.getText();
        if(cityName.isEmpty() && communityName.isEmpty()){
            JOptionPane.showMessageDialog(this,"Community name and city name cannot be empty.");
            return;
        }
        if (cityName.isEmpty()){
            cityName=null;
        }
        if (communityName.isEmpty()){
            communityName=null;
        }
            List <Hospital> hospital = system.searchHospital(communityName, cityName);
            populateTable(hospital);
        
    }//GEN-LAST:event_BtnSearchActionPerformed

    private void patientSearchCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientSearchCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientSearchCityActionPerformed


     void populateTable(List <Hospital> hospital){
    DefaultTableModel model=(DefaultTableModel) jTableHospital.getModel(); 
    model.setRowCount(0);
    for(Hospital h: hospital){
        Object[] row = new Object[3];
        row[0] = h.getName();
        row[1] = h.getCity();
        row[2] = h.getCommunityName();
        model.addRow(row);
    }
   
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSearch;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHospital;
    private javax.swing.JTextField patientSearchCity;
    private javax.swing.JTextField patientSearchCommunityName;
    // End of variables declaration//GEN-END:variables
}
